"""
Seeds 100+ interview questions with embeddings into Supabase.
Run once: python -m app.agent.seed_questions
"""
import asyncio
from openai import AsyncOpenAI
from app.config import settings
from app.lib.supabase import supabase

QUESTIONS = [
  # ── BEHAVIORAL (30 QUESTIONS) ──
  {"text": "Tell me about yourself.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Current role summary", "Key achievements", "Why this role"]},
  {"text": "Tell me about a time you failed. What did you learn?", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Specific failure", "Personal responsibility", "Concrete lesson", "What changed after"]},
  {"text": "Describe a conflict with a teammate and how you resolved it.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Specific conflict", "Your approach", "Resolution", "Relationship outcome"]},
  {"text": "Tell me about your greatest professional achievement.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Quantified impact", "Your specific role", "Team collaboration", "Skills demonstrated"]},
  {"text": "Where do you see yourself in 5 years?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Growth ambition", "Alignment with role", "Realistic trajectory"]},
  {"text": "Describe a situation where you had to work under a tight deadline.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Task prioritization", "Communication with stakeholders", "Outcome of project"]},
  {"text": "How do you handle feedback or criticism?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Receptiveness", "Active listening", "Behavior adjustment", "Continuous learning"]},
  {"text": "Tell me about a time you had to learn a new technology quickly.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Reason for learning", "Method of learning", "Application to project", "Outcome"]},
  {"text": "Give an example of a time you went above and beyond for a customer or project.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Initial scope", "Extra effort taken", "Why it mattered", "Resulting impact"]},
  {"text": "Describe a time when you disagreed with a manager's decision. What did you do?", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Respectful disagreement", "Data-driven arguments", "Support of final decision", "Outcome"]},
  {"text": "Tell me about a time you had to deal with ambiguity in a project.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Clarification steps", "Iterative progress", "Risk mitigation", "Final delivery"]},
  {"text": "How do you manage stress and prevent burnout?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Self-awareness signs", "Boundaries set", "Time management techniques", "Leisure balance"]},
  {"text": "Describe a time you had to influence someone without formal authority.", "category": "behavioral", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Building trust", "Data and reasoning", "WIIFM (What's in it for them)", "Successful consensus"]},
  {"text": "Tell me about a time you made a mistake at work and how you handled it.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Immediate ownership", "Solution search", "Team communication", "Process change to avoid recurrence"]},
  {"text": "What type of work environment do you thrive in?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Collaboration preferences", "Feedback loop speed", "Autonomy level"]},
  {"text": "Describe a time you had to explain a complex technical issue to a non-technical person.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Use of analogies", "Removing jargon", "Active listening/confirmation", "Successful outcome"]},
  {"text": "Tell me about a time you worked with someone whose style was very different from yours.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Style differences noted", "Adaptations made", "Mutual benefits", "Project success"]},
  {"text": "How do you decide what tasks to prioritize when everything is urgent?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Prioritization matrix", "Stakeholder communication", "Impact assessment", "Flexibility"]},
  {"text": "Tell me about a time you stepped up as a leader when not officially asked to.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Identified gap", "Initiative taken", "Team coordination", "Resulting improvements"]},
  {"text": "What is the biggest risk you have taken in your career, and how did it turn out?", "category": "behavioral", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Risk explanation", "Calculations and planning", "Outcome and learnings"]},
  {"text": "Describe a project that didn't go as planned. How did you react?", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Deviations identified", "Pivot strategies", "Communication of delay/issues", "Learnings"]},
  {"text": "How do you stay updated with industry trends and technology advancements?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Resources used", "Side projects", "Sharing knowledge with team"]},
  {"text": "Tell me about a time you had to give difficult feedback to a coworker.", "category": "behavioral", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Feedback structure", "Empathy combined with honesty", "Actionable next steps", "Relationship preservation"]},
  {"text": "What motivated you to apply for this specific role and company?", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Company mission alignment", "Technical challenges matching skills", "Career goals"]},
  {"text": "Tell me about a time when you had to make a decision without all the information you wanted.", "category": "behavioral", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Calculated assumptions", "Consulting domain experts", "Mitigating downside", "Outcome"]},
  {"text": "Describe your ideal manager.", "category": "behavioral", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Communication preferences", "Autonomy requirements", "Support for growth"]},
  {"text": "What would you do if a project you worked on for months was cancelled?", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Professionalism", "Salvaging reusable code/docs", "Moving forward", "Emotional resilience"]},
  {"text": "How do you handle disagreement in a technical architecture meeting?", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Focus on goals", "Writing down pros/cons", "Seeking consensus", "Agree and commit"]},
  {"text": "Tell me about a time you mentored a junior engineer.", "category": "behavioral", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Teaching method", "Patience and availability", "Career outcome for mentee"]},
  {"text": "If you could change one decision you made in your last job, what would it be?", "category": "behavioral", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Self-reflection", "Hindsight adjustment", "No blame gaming", "Learnings implemented since"]},

  # ── TECHNICAL — FRONTEND (20 QUESTIONS) ──
  {"text": "Explain how the React virtual DOM works.", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["Virtual DOM definition", "Diffing algorithm", "Reconciliation", "Performance benefit"]},
  {"text": "What is the difference between useEffect and useLayoutEffect?", "category": "technical", "difficulty": "hard",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Timing difference", "Use cases", "Performance implications", "Example"]},
  {"text": "How does CSS specificity work?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Specificity hierarchy", "Calculation method", "!important caveat", "Example"]},
  {"text": "Explain the difference between Client-Side Rendering (CSR) and Server-Side Rendering (SSR).", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["Initial load time", "SEO implications", "Data fetching location", "Hybrid models"]},
  {"text": "What is event delegation in JavaScript and why is it useful?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Event bubbling", "Single event listener", "Memory optimization", "Dynamic child elements"]},
  {"text": "How do closures work in JavaScript?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Lexical scoping", "Accessing outer function scopes", "Encapsulation/private variables", "Memory leaks risk"]},
  {"text": "What are React Server Components (RSC) and how do they differ from client components?", "category": "technical", "difficulty": "hard",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["Zero bundle size", "Direct backend access", "No state/hooks on server", "Reconciliation hybrid"]},
  {"text": "What is the box model in CSS?", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Content, padding, border, margin", "box-sizing property", "Border-box vs content-box"]},
  {"text": "Explain how promises and async/await work in JavaScript.", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend", "fullstack", "backend"],
   "ideal_answer_points": ["Promise states", "Event loop & microtasks", "Error handling with try/catch", "Syntactic sugar benefits"]},
  {"text": "How do you optimize a React application's rendering performance?", "category": "technical", "difficulty": "hard",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["React.memo, useMemo, useCallback", "Virtualization of lists", "Code splitting/lazy loading", "Reducing state changes"]},
  {"text": "What is the difference between state and props in React?", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["State is local/mutable", "Props are read-only/passed down", "Triggering re-renders"]},
  {"text": "Explain the concepts of debouncing and throttling.", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Debouncing delays execution", "Throttling limits frequency", "Real-world examples (search inputs vs scrolling)"]},
  {"text": "What is cross-site scripting (XSS) and how do you prevent it in frontend code?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["Malicious script injection", "Sanitization & escaping", "Content Security Policy (CSP)", "Framework protections"]},
  {"text": "How do you implement internationalization (i18n) in a web app?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Translation dictionaries", "Locale detection", "Handling dynamic dates/currencies", "SSR considerations"]},
  {"text": "What are CSS Modules and styled-components, and what problems do they solve?", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["CSS scoping", "Class name conflicts prevention", "Dynamic styling based on props"]},
  {"text": "Explain the lifecycle of a React component.", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Mounting, updating, unmounting", "Class lifecycle methods vs useEffect dependencies"]},
  {"text": "How does CORS (Cross-Origin Resource Sharing) work?", "category": "technical", "difficulty": "medium",
   "role_tags": ["frontend", "fullstack", "backend"],
   "ideal_answer_points": ["Browser security mechanism", "Preflight OPTIONS requests", "CORS headers (Access-Control-Allow-Origin)"]},
  {"text": "Explain the difference between localstorage, sessionstorage, and cookies.", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["Storage limits", "Expiration behaviors", "HTTP request overhead", "Security flags (HttpOnly)"]},
  {"text": "What is hydration in Next.js?", "category": "technical", "difficulty": "hard",
   "role_tags": ["frontend", "fullstack"],
   "ideal_answer_points": ["HTML serving", "Attaching JS event listeners", "Hydration mismatch errors", "Solutions"]},
  {"text": "Explain how absolute positioning differs from relative positioning in CSS.", "category": "technical", "difficulty": "easy",
   "role_tags": ["frontend"],
   "ideal_answer_points": ["Relative is relative to self", "Absolute is relative to nearest positioned ancestor", "Document flow removal"]},

  # ── TECHNICAL — BACKEND (20 QUESTIONS) ──
  {"text": "What is the difference between SQL and NoSQL databases?", "category": "technical", "difficulty": "easy",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Schema vs schemaless", "ACID vs BASE", "Scaling differences", "When to use each"]},
  {"text": "Explain REST vs GraphQL.", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["REST principles", "GraphQL advantages", "Over-fetching problem", "When to use each"]},
  {"text": "What are database transactions and ACID properties?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Atomicity, Consistency, Isolation, Durability", "Transaction rollbacks", "Concurrent access control"]},
  {"text": "How does database indexing work, and what are the trade-offs?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["B-tree or Hash structures", "Fast reads", "Slower writes/updates", "Storage overhead"]},
  {"text": "What is the difference between horizontal and vertical scaling?", "category": "technical", "difficulty": "easy",
   "role_tags": ["backend", "system_design"],
   "ideal_answer_points": ["Scale up vs scale out", "Single point of failure", "Distributed systems complexity", "Cost considerations"]},
  {"text": "Explain the concept of connection pooling.", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Database connection overhead", "Recycling open connections", "Max connections limit protection"]},
  {"text": "How do WebSockets differ from HTTP polling?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Full duplex vs half duplex", "Persistent TCP connection", "Real-time updates efficiency", "Server overhead"]},
  {"text": "What is OAuth 2.0 and how does the Authorization Code flow work?", "category": "technical", "difficulty": "hard",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Authorization vs Authentication", "Tokens (Access, ID, Refresh)", "Redirect URI authorization", "Server-side code exchange"]},
  {"text": "How do you secure a REST API?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["HTTPS/TLS", "JWT/Token auth", "Rate limiting", "Input validation & SQL Injection prevention"]},
  {"text": "What is a message queue and when would you use one?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "system_design"],
   "ideal_answer_points": ["Asynchronous task execution", "Decoupling microservices", "RabbitMQ / Kafka examples", "Backpressure handling"]},
  {"text": "Explain the difference between process and thread.", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Independent memory space vs shared memory", "Context switching overhead", "Concurrency vs parallelism"]},
  {"text": "How does Redis cache data and what are eviction policies?", "category": "technical", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["In-memory key-value store", "LRU / LFU eviction", "Cache invalidation strategies"]},
  {"text": "What is an ORM (Object-Relational Mapping) and what are its pros and cons?", "category": "technical", "difficulty": "easy",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Developer productivity", "N+1 query problem", "Database independence", "Performance tuning limitations"]},
  {"text": "Explain garbage collection in managed languages (like Java, Python, Go).", "category": "technical", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Memory allocation", "Reference counting vs tracing", "Stop-the-world pauses", "Optimizations"]},
  {"text": "What is the CAP Theorem?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "system_design"],
   "ideal_answer_points": ["Consistency, Availability, Partition tolerance", "Pick two rule", "Real-world trade-offs"]},
  {"text": "Explain how rate limiting works in backend services.", "category": "technical", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Token bucket / Leaky bucket algorithms", "Redis implementations", "HTTP 429 Too Many Requests response"]},
  {"text": "What is N+1 query problem and how do you resolve it?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Unoptimized ORM relations fetching", "Eager loading (joins/preloading)", "Batching queries"]},
  {"text": "What is the difference between symmetric and asymmetric encryption?", "category": "technical", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Single key vs public/private key pair", "Performance differences", "SSL/TLS handshake application"]},
  {"text": "Explain the MVC (Model-View-Controller) architecture pattern.", "category": "technical", "difficulty": "easy",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Separation of concerns", "Data model vs UI rendering vs business logic routing"]},
  {"text": "How do you debug a performance issue (CPU/memory leak) in a production server?", "category": "technical", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["APM profiling tools", "Heap dumps analysis", "Checking db slow queries logs", "Network metrics monitoring"]},

  # ── SYSTEM DESIGN (15 QUESTIONS) ──
  {"text": "How would you design a URL shortener like bit.ly?", "category": "system_design", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Requirements clarification", "Hash function", "Database schema", "Scaling strategy", "Cache layer"]},
  {"text": "Design a real-time chat system like WhatsApp.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["WebSocket vs polling", "Message storage", "Delivery guarantees", "Scale to millions"]},
  {"text": "How would you design Netflix's video streaming?", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["CDN usage", "Encoding pipeline", "Adaptive bitrate", "Global distribution"]},
  {"text": "Design an autocomplete/search suggestion service.", "category": "system_design", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Trie data structure", "Caching suggestions", "Updating index async", "Low-latency API"]},
  {"text": "How would you design a rate limiter for a public API?", "category": "system_design", "difficulty": "medium",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Token bucket / Sliding window algorithms", "Distributed system sync", "IP vs Client-token filtering", "Fast cache layer"]},
  {"text": "Design a web crawler.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["URL frontier", "HTML parsing & link extraction", "De-duplication layer", "Robots.txt respect", "Distributed workers"]},
  {"text": "How would you design a notification service supporting SMS, Email, and Push notifications?", "category": "system_design", "difficulty": "medium",
   "role_tags": ["backend", "fullstack"],
   "ideal_answer_points": ["Message queue", "Priority lanes", "Vendor integrations fallback", "Tracking status analytics"]},
  {"text": "Design a collaborative document editor like Google Docs.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["frontend", "backend", "fullstack"],
   "ideal_answer_points": ["Operational Transformation (OT) or CRDT", "WebSocket communication", "Conflict resolution", "Document snapshots"]},
  {"text": "Design a news feed system like Twitter or Facebook.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Push vs pull feed generation", "Caching active feeds", "Fanout database performance", "Rank algorithms"]},
  {"text": "Design a ride-sharing service like Uber.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Geospatial indexing (quadtree/H3)", "Location updates stream", "Matching algorithms", "Payment/receipt async workflow"]},
  {"text": "Design an e-commerce flash sale system (highly concurrent checkouts).", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Inventory pre-allocation in Redis", "Queue checkout requests", "Idempotent transactions", "Preventing double buy"]},
  {"text": "Design a key-value store database.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Data replication (Master-Slave)", "Quorum consensus", "Partitioning (Consistent hashing)", "LSM trees or SSTables"]},
  {"text": "Design a metrics monitoring and alerting dashboard (like Prometheus/Grafana).", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Time series database", "Data aggregation/downsampling", "Alert triggers queue", "Pull vs push metrics collections"]},
  {"text": "How would you design a content delivery network (CDN)?", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["Edge caching servers", "GeoDNS routing", "Cache invalidation propagation", "Dynamic content acceleration"]},
  {"text": "Design a distributed payment processing system.", "category": "system_design", "difficulty": "hard",
   "role_tags": ["backend"],
   "ideal_answer_points": ["2-phase commit / Saga pattern", "Idempotency keys", "Handling partial failures", "PCI compliance security"]},

  # ── LEADERSHIP (15 QUESTIONS) ──
  {"text": "How do you handle a team member who is underperforming?", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["1-on-1 feedback", "Root cause identification", "Performance Improvement Plan (PIP)", "Continuous monitoring"]},
  {"text": "Describe your approach to delegating tasks to team members.", "category": "leadership", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Assessing skills & career interests", "Setting clear expectations", "Avoiding micromanagement", "Providing feedback"]},
  {"text": "Tell me about a time you had to resolve a major disagreement between two tech leads.", "category": "leadership", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Active listening", "Focusing on business constraints", "Objective evaluation framework", "Final compromise and alignment"]},
  {"text": "How do you align technical roadmap with business goals?", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Translating tech debt into business impact", "Involving product stakeholders early", "Clear prioritization criteria"]},
  {"text": "Tell me about a time you had to deliver bad news to your team.", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Directness and transparency", "Providing rationale", "Active empathy", "Action plan for next steps"]},
  {"text": "How do you foster a culture of diversity and inclusion in your engineering team?", "category": "leadership", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Unbiased hiring practices", "Encouraging voice from all levels", "Psychological safety", "Zero-tolerance for discrimination"]},
  {"text": "What is your philosophy on technical debt?", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Debt vs leverage distinction", "Tracking and visibility", "Allocating a fixed percentage of resources", "Refactoring as product investment"]},
  {"text": "Describe a time you failed as a leader.", "category": "leadership", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Ownership of mistake", "Impact assessment", "Vulnerability with team", "Concrete actions taken to fix"]},
  {"text": "How do you manage remote team engagement and collaboration?", "category": "leadership", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Asynchronous docs first", "Structured virtual syncs", "Fostering social connection", "Focusing on output over hours"]},
  {"text": "How do you handle high-pressure situations or production incidents as a leader?", "category": "leadership", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Calm communication", "Clear role assignment (Incident Commander)", "Blameless post-mortem", "Fixing root causes"]},
  {"text": "How do you advocate for your team's budget or headcount increases?", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Data-driven velocity metrics", "Quantifying missed business opportunities", "Clear planning"]},
  {"text": "Describe how you hire engineering talent.", "category": "leadership", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Defining job requirements", "Structuring interview rubrics", "Minimizing bias", "Candidate experience focus"]},
  {"text": "How do you help your team members grow in their careers?", "category": "leadership", "difficulty": "medium",
   "role_tags": ["all"],
   "ideal_answer_points": ["Setting clear growth paths", "Providing stretch opportunities", "Regular career reviews", "Sponsorship and promotion cases"]},
  {"text": "What is the most difficult decision you had to make as a manager?", "category": "leadership", "difficulty": "hard",
   "role_tags": ["all"],
   "ideal_answer_points": ["Layoffs or firing", "Trade-offs and criteria used", "Empathy and respect in execution", "Communication to team"]},
  {"text": "How do you build trust with your team?", "category": "leadership", "difficulty": "easy",
   "role_tags": ["all"],
   "ideal_answer_points": ["Transparency", "Keeping commitments", "Shielding them from noise", "Empowering rather than policing"]}
]

async def embed_text(client: AsyncOpenAI, text: str) -> list[float]:
  """Generate embedding using NVIDIA NIM embedding model."""
  response = await client.embeddings.create(
    model="nvidia/llama-nemotron-embed-1b-v2",
    input=text,
    encoding_format="float",
    extra_body={"input_type": "query"}
  )
  return response.data[0].embedding


async def seed():
  client = AsyncOpenAI(
    api_key=settings.nvidia_api_key,
    base_url=settings.nvidia_base_url
  )
  print(f"Seeding {len(QUESTIONS)} questions...")
  for i, q in enumerate(QUESTIONS):
    try:
      embedding = await embed_text(client, q["text"])
      supabase.table("questions").upsert({
        **q,
        "embedding": embedding
      }).execute()
      print(f"  [{i+1}/{len(QUESTIONS)}] {q['text'][:50]}...")
    except Exception as e:
      print(f"  [{i+1}/{len(QUESTIONS)}] Failed: {q['text'][:30]}... Error: {e}")
  print("Done!")

if __name__ == "__main__":
  asyncio.run(seed())
